<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_910-11230359567</name>
   <tag></tag>
   <elementGuidId>759b19bb-63b4-49f0-8f4c-70ab10b421f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.text-right.ng-scope > a.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='searchResult']/div/table/tbody/tr/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6bd8afcb-96fb-4376-bd01-1749da89c8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/#/Sales/pos?inv=3839519</value>
      <webElementGuid>7cb8dd82-f588-4735-9df0-11dcf48e3b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orderno</name>
      <type>Main</type>
      <value>910-11230359567</value>
      <webElementGuid>cb8dc95f-0ca7-48a0-965c-110f07f45d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>a242b637-34c4-4ecc-8802-fbd795420cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>910-11230359567</value>
      <webElementGuid>2ec08fed-eff4-4896-9c5b-843a46ade95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchResult&quot;)/div[@class=&quot;row&quot;]/table[@class=&quot;table table-striped table-bordered table-hover table-responsive active table-item ng-scope&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[@class=&quot;text-right ng-scope&quot;]/a[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>cb0dfba2-772a-4e6c-9a81-cf2ebfe7dbfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchResult']/div/table/tbody/tr/td[2]/a</value>
      <webElementGuid>9f23e8be-8d7d-4c39-b3a5-f4ff879cae33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'910-11230359567')]</value>
      <webElementGuid>f2fb945c-4bb9-4634-91ea-71c0d5cc1b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/#/Sales/pos?inv=3839519')]</value>
      <webElementGuid>76ae9186-356d-4cb1-beef-7919046711df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>6edf93fe-db84-4ddc-8a0e-1555dde1dd6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/#/Sales/pos?inv=3839519' and (text() = '910-11230359567' or . = '910-11230359567')]</value>
      <webElementGuid>d344d24c-6f27-43a0-97a2-0a8a4d2a4e1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
