<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Non-StocksProduct Link</name>
   <tag></tag>
   <elementGuidId>ba9e9cf4-df54-46dd-923a-9c50d962d6da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='mainMenu']/li[3]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.dropdown.ng-scope.open > ul.dropdown-menu > li.ng-scope > a.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>37c16c12-3d83-4b66-96c3-6ffd95294648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/NonStocks/ProductLink</value>
      <webElementGuid>161dfb19-5f19-4b43-ad50-608274c80249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>9b3ff093-3a37-4fc3-9c9f-cfe3565a26f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Non-Stocks/Product Link</value>
      <webElementGuid>e0791424-171f-4ac7-9026-06e501f48a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainMenu&quot;)/li[@class=&quot;dropdown ng-scope open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[@class=&quot;ng-scope&quot;]/a[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>9fa2ad1e-6c8e-43e9-964b-3f22f8997c69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenu']/li[3]/ul/li/a</value>
      <webElementGuid>3690f750-6e9a-488e-af35-a7462530dd58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Non-Stocks/Product Link')]</value>
      <webElementGuid>4cfb018f-132a-4486-b25a-d045fdda592a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/NonStocks/ProductLink')]</value>
      <webElementGuid>ec70fa24-edaa-40f4-837c-f2a86b345222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/a</value>
      <webElementGuid>0be98dc5-6c3a-44ae-8076-ccd827135361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/NonStocks/ProductLink' and (text() = 'Non-Stocks/Product Link' or . = 'Non-Stocks/Product Link')]</value>
      <webElementGuid>1f59fc22-955e-4212-805c-8e8bc0fcbbd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
