<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Authorise</name>
   <tag></tag>
   <elementGuidId>3456223d-2217-486d-a879-9f295b462a64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.col-lg-offset-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e605ef0-1bfa-4798-b643-ae547755e001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary col-lg-offset-8</value>
      <webElementGuid>1ccc6c86-281e-44da-b8c1-3a3bcef110c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>authorise()</value>
      <webElementGuid>c251a420-065d-4ee7-a8a7-90c77e550492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>disableAuthorise()</value>
      <webElementGuid>f63362af-97b6-4b8e-8ce7-5ec7d7d2ce4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Authorise</value>
      <webElementGuid>ab5c58d6-4168-4324-bec6-b1c9e977db9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;ng-scope full-screen modal-open&quot;]/div[@class=&quot;modal fade ng-isolate-scope in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-content authorization-modal ng-scope&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5&quot;]/form[@class=&quot;ng-valid ng-valid-required ng-dirty ng-valid-parse&quot;]/article[@class=&quot;authorisation-credentials row form-horizontal&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;form-group&quot;]/button[@class=&quot;btn btn-primary col-lg-offset-8&quot;]</value>
      <webElementGuid>7303e715-c59f-4786-99d9-f5f8e2e985c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/button</value>
      <webElementGuid>11e4c235-c4c7-44d6-81be-5468ec51a565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Authorise' or . = 'Authorise')]</value>
      <webElementGuid>d4c54345-9410-4387-bb63-a0d87fed7ee2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
