<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>570ecd03-f37d-4151-8a2a-66c0ca191efc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonSearch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>373fd357-9454-42f8-8bd9-4a2320580de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonSearch</value>
      <webElementGuid>be7994f4-835f-49e9-9f0d-82304a788534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search btn btn-primary  btn-lg</value>
      <webElementGuid>c6854f43-cd80-4e17-9a9a-4961c9aeffe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>a86229c1-a5a7-4927-925c-08fffc79c0fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>searchButtonClick()</value>
      <webElementGuid>e9a468f5-3446-49b6-b38d-1c7ffbb66c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!searchBottonEnabled</value>
      <webElementGuid>378ea8d5-d3f0-45d7-becc-65ca01b3e7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Search
                </value>
      <webElementGuid>c7b40ee2-568b-4bc7-8d75-096f5a6a5109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonSearch&quot;)</value>
      <webElementGuid>591b23f2-ba32-4a49-9317-91c4c150aaa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttonSearch']</value>
      <webElementGuid>2614c0b7-ad31-4229-8e08-e38df0bf3f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer']/div/div/div[2]/div/div/button[2]</value>
      <webElementGuid>f4730c8d-d99c-409d-8988-ab3fafa629d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>7d594f9c-9551-4eb8-b167-3b986dbd3959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buttonSearch' and (text() = '
                    Search
                ' or . = '
                    Search
                ')]</value>
      <webElementGuid>f29e3980-64b2-4510-9cde-5e01a2420ca6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
