<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pay</name>
   <tag></tag>
   <elementGuidId>1f87227e-13be-439e-8f3c-2282489f6bf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paymentBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='paymentBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7d0c4200-a1ff-43f4-95e4-71e3a553cff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ok btn btn-lg btn-block btn-primary ng-scope</value>
      <webElementGuid>e0a55c35-0e37-4a1c-b123-179365b66c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>savePayment()</value>
      <webElementGuid>daea45bb-9b11-4500-8a2c-bdd415793b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>checkPayment()</value>
      <webElementGuid>c10d844d-6f62-42f4-a30a-c3d8c575c54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>sections.buttonPay.visible</value>
      <webElementGuid>951ee3b7-a4ee-4de6-a99d-3cfeb5f3df05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentBtn</value>
      <webElementGuid>83a9afef-12fe-4554-a13f-e29d929de57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pay
                    </value>
      <webElementGuid>4f07f9dc-9e52-42de-8ece-bdd3c7fd4eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentBtn&quot;)</value>
      <webElementGuid>db5266c4-5805-47f9-abb3-9c6c35ebafda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='paymentBtn']</value>
      <webElementGuid>32843099-9f94-4243-ae2a-7ba884d463f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-action']/div/div/button</value>
      <webElementGuid>a663e8d0-330c-41b2-8357-4250070d1a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/button</value>
      <webElementGuid>dfaddd41-2b86-4e87-945e-aecba21bce05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'paymentBtn' and (text() = 'Pay
                    ' or . = 'Pay
                    ')]</value>
      <webElementGuid>b7abe356-5438-401f-995e-f2f43e47172f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
