<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Basket1</name>
   <tag></tag>
   <elementGuidId>0b076e37-b663-47f9-95e3-f223d9fba1fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='body']/div/section/div/div/div[2]/div/div[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.tab-select.btn-default.btn-lg.btn-block.glyphicons.shopping_cart.bb-btn-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>60fc01df-dcbd-498b-9d1f-b2a29f581280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>setView('itemList')</value>
      <webElementGuid>82c6d1c0-8500-4ba0-a5d4-6fd4f960ca9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn tab-select btn-default btn-lg btn-block glyphicons shopping_cart bb-btn-active</value>
      <webElementGuid>8be6f329-80e4-4326-8a16-06e48c710c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'btn-primary active': views.itemList.visible}</value>
      <webElementGuid>1d639f46-9aac-4a82-b61e-50a8e1bd60af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                  Basket1
                            </value>
      <webElementGuid>b088a661-2463-48b3-83b8-4d28c044aef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;pos-sales ng-scope saleContainer&quot;]/section[@class=&quot;row sale-main&quot;]/div[@class=&quot;col-md-9 col-sm-10&quot;]/div[@class=&quot;row text-center&quot;]/div[@class=&quot;col-lg-11 col-md-11&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3 col-md-3 no-margin no-pad basket-button&quot;]/button[@class=&quot;btn tab-select btn-default btn-lg btn-block glyphicons shopping_cart bb-btn-active&quot;]</value>
      <webElementGuid>23cc4517-96fe-4ea2-a14f-61d8ca671788</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='body']/div/section/div/div/div[2]/div/div[3]/button</value>
      <webElementGuid>677459b9-39ac-4de9-8c77-5391a6658de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>62cb3947-4198-41bc-8acf-4952f570e0fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                                  Basket1
                            ' or . = '
                                  Basket1
                            ')]</value>
      <webElementGuid>e55c293e-945c-47a2-bfd9-8b3f67f4e50b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
