<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FURNITURE</name>
   <tag></tag>
   <elementGuidId>e6201fcc-5850-468d-8f61-e61e7e88fa40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='products']/div/div/section/div[2]/div/div/div[2]/div/div/div/div[2]/div/div[8]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a1ecb2fc-8cd3-4b3f-a142-fec65da57c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>2612e288-2fcb-4c4f-99ee-2652bf6e8cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FURNITURE</value>
      <webElementGuid>12ca6a9b-6d2f-4af8-9677-454e879b60b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products&quot;)/div[@class=&quot;facetsearch-container row ng-scope&quot;]/div[@class=&quot;col-lg-12 col-md-12&quot;]/section[@class=&quot;facetSearch medium&quot;]/div[@class=&quot;facet-data-container&quot;]/div[@class=&quot;facet-data&quot;]/div[@class=&quot;row facetrow fieldsRow&quot;]/div[@class=&quot;searchFields touch-friendly&quot;]/div[@class=&quot;row facetrow&quot;]/div[@class=&quot;col-lg-12 col-md-12&quot;]/div[@class=&quot;col-lg-12 col-md-12 search-grid&quot;]/div[@class=&quot;touch-scroll-fields&quot;]/div[@class=&quot;touch-search-field ng-scope&quot;]/div[@class=&quot;col-lg-3 col-md-3 grid-item touch-field-value merchandisingLevel_1&quot;]/div[@class=&quot;grid-content&quot;]/div[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>d8422514-3854-4ff7-a848-7111bf5627a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='products']/div/div/section/div[2]/div/div/div[2]/div/div/div/div[2]/div/div[8]/div/div</value>
      <webElementGuid>adecf8a8-8e67-4a9e-a23a-fb695aa67922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div</value>
      <webElementGuid>8b22cd17-c89c-4104-82ef-28e6be8c40e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'FURNITURE' or . = 'FURNITURE')]</value>
      <webElementGuid>9cdfeddc-ac34-4cfe-b3da-54759f2cc826</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
