<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sale Completed</name>
   <tag></tag>
   <elementGuidId>e427f5c0-9f07-41fc-ac8a-427bb689fa90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='completedMsg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#completedMsg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6b342001-8c53-439f-a61c-371a297ec7c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-body</value>
      <webElementGuid>a89ce9b2-449a-40f7-b61a-0d29c01a3133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>completedMsg</value>
      <webElementGuid>776a2c2e-422e-4727-a596-ccc397c6e0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sale Completed</value>
      <webElementGuid>29fda29d-1191-489f-82b1-3da73d052c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;completedMsg&quot;)</value>
      <webElementGuid>1345636e-95cd-4411-9e2b-d853d9d78174</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='completedMsg']</value>
      <webElementGuid>50f8ac35-f51b-433e-9a21-4033fb390e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/div[2]/div/div/div/div[2]</value>
      <webElementGuid>7440c4ac-bf59-43ae-8cdc-4b30634bab88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>27de2e7c-f986-42aa-a305-d08fa9bd4c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'completedMsg' and (text() = 'Sale Completed' or . = 'Sale Completed')]</value>
      <webElementGuid>c6835b9e-f8ae-4587-98bf-6f54cd837d7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
