<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Faulty Goods</name>
   <tag></tag>
   <elementGuidId>91b3a9c8-edc7-4563-9154-98a424f54912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.list-item.ng-binding.ng-scope.selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='return-list']/div[3]/div/div[2]/div/list/div[3]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4f8adc54-6836-40ab-bd6d-0efdd727ae13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-item ng-binding ng-scope selected</value>
      <webElementGuid>4c48fd65-1d85-42ff-ac67-1652a67dddac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>list.length > 0</value>
      <webElementGuid>c013cb20-8dab-40c4-9c8e-dea2e493c85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>item in list | filter:search</value>
      <webElementGuid>c6b8ad39-0b75-4b44-9d19-cb96c85ec759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>selectItem(item)</value>
      <webElementGuid>ce6d21af-6213-4180-aa6d-74e0606d3848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idx</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3370d0c8-0666-45db-bb50-c4c295192156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'selected':hoveredIndex == $index}</value>
      <webElementGuid>664758b1-0f99-440e-b131-e947a3ca8663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseover</name>
      <type>Main</type>
      <value>hoverItem($index)</value>
      <webElementGuid>8179010a-6fd0-4acf-9dbf-9c4b220d0c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseleave</name>
      <type>Main</type>
      <value>resetHoverItem()</value>
      <webElementGuid>1daf3612-b64c-4749-b1cf-0036f438ccf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Faulty Goods</value>
      <webElementGuid>e9b4e6a4-25f1-464e-82c2-5fc6d963bfa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;return-list&quot;)/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;col-lg-12 col-md-12 item bg-warning&quot;]/div[@class=&quot;row ng-scope bg-info&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-md-offset-1 pull-right&quot;]/list[@class=&quot;form-control ng-pristine ng-untouched ng-valid ng-isolate-scope has-error&quot;]/div[@class=&quot;list-options ng-scope&quot;]/div[@class=&quot;list-item-container ng-scope&quot;]/div[@class=&quot;list-item ng-binding ng-scope selected&quot;]</value>
      <webElementGuid>f827df93-2e31-49d9-922a-66df7f6d7256</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='return-list']/div[3]/div/div[2]/div/list/div[3]/div[2]/div[2]</value>
      <webElementGuid>dd8d65b6-c323-45ef-9958-accb0b358ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]</value>
      <webElementGuid>4d6106a8-fb27-4e96-9e94-44f5f60452de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Faulty Goods' or . = 'Faulty Goods')]</value>
      <webElementGuid>20b794d8-ab21-45c3-8f87-8d6d10d7399b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
