<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DINING</name>
   <tag></tag>
   <elementGuidId>509a17ae-f0eb-42e5-b0e7-b9354d9d78f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='products']/div/div/section/div[2]/div/div/div[2]/div/div/div/div[2]/div[2]/div[3]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf8699e2-5a1b-4c44-9822-ad36aff45a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>13147978-6769-4647-bdb1-6f34aee0b84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DINING</value>
      <webElementGuid>040cbd63-581e-4c8a-bbb2-2a72e1b8230f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products&quot;)/div[@class=&quot;facetsearch-container row ng-scope&quot;]/div[@class=&quot;col-lg-12 col-md-12&quot;]/section[@class=&quot;facetSearch medium&quot;]/div[@class=&quot;facet-data-container&quot;]/div[@class=&quot;facet-data&quot;]/div[@class=&quot;row facetrow fieldsRow&quot;]/div[@class=&quot;searchFields touch-friendly&quot;]/div[@class=&quot;row facetrow&quot;]/div[@class=&quot;col-lg-12 col-md-12&quot;]/div[@class=&quot;col-lg-12 col-md-12 search-grid&quot;]/div[@class=&quot;touch-scroll-fields&quot;]/div[@class=&quot;touch-search-field ng-scope&quot;]/div[@class=&quot;col-lg-3 col-md-3 grid-item touch-field-value merchandisingLevel_2&quot;]/div[@class=&quot;grid-content&quot;]/div[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>d5ae9b4a-9308-461c-a948-140777f3ff1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='products']/div/div/section/div[2]/div/div/div[2]/div/div/div/div[2]/div[2]/div[3]/div/div</value>
      <webElementGuid>3ee933ca-8dc2-45d3-94e4-ca3810700eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div/div</value>
      <webElementGuid>c183dc9b-cb3c-4bb6-947c-3ec8caa22c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DINING' or . = 'DINING')]</value>
      <webElementGuid>44939746-67f0-44f5-8a70-5a588896e085</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
