<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1 - Steve Brickell</name>
   <tag></tag>
   <elementGuidId>b6b1b832-76fe-4718-9607-870960eec947</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//list[@id='soldBy']/div[3]/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.list-item.ng-binding.ng-scope.selected</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>292affde-2ba7-4970-aa11-51f4e4440a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-item ng-binding ng-scope selected</value>
      <webElementGuid>1e4f4ddc-612c-4a65-8e7c-a5fdccfa8c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>list.length > 0</value>
      <webElementGuid>8bfe48c7-8634-4c50-bb70-2e2c69fae127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>item in list | filter:search</value>
      <webElementGuid>1dec3c97-9ce8-49b6-bc79-c56df0703d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>selectItem(item)</value>
      <webElementGuid>d205b78f-8c70-435e-b2fa-59e5ed5d6b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idx</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>41e51d49-de2d-4312-b681-40298eae78a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'selected':hoveredIndex == $index}</value>
      <webElementGuid>8ba6a337-758a-4460-abf1-0a9a4b33cf24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseover</name>
      <type>Main</type>
      <value>hoverItem($index)</value>
      <webElementGuid>0db85d5f-e592-4589-9951-d708aa53b454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseleave</name>
      <type>Main</type>
      <value>resetHoverItem()</value>
      <webElementGuid>9b9359f4-6151-499a-bd45-0c9121a9d1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 - Steve Brickell</value>
      <webElementGuid>ece077f8-885f-41d6-b063-cd91b8b05814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;soldBy&quot;)/div[@class=&quot;list-options ng-scope&quot;]/div[@class=&quot;list-item-container ng-scope&quot;]/div[@class=&quot;list-item ng-binding ng-scope selected&quot;]</value>
      <webElementGuid>21b0aff2-6a0b-460a-82a7-55d4d9788d6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//list[@id='soldBy']/div[3]/div[2]/div[2]</value>
      <webElementGuid>bfc2454c-8d7c-4522-aa78-811cfb2b124f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]</value>
      <webElementGuid>0bd322cd-6896-4dec-96e5-8a36d310cc46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1 - Steve Brickell' or . = '1 - Steve Brickell')]</value>
      <webElementGuid>bfd76035-06ea-49b4-9faa-a68f3ca61647</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
