<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_5 PC DINING SET METAL</name>
   <tag></tag>
   <elementGuidId>552b4bbc-c796-45a3-b4d1-0d89de3623f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='products']/div/div/section/div[2]/div/div/div[2]/div/div/div/div[2]/div[3]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-lg-3.col-md-3.grid-item.touch-field-value.merchandisingLevel_3 > div.grid-content > div.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c1a51470-07ea-4512-9d03-f53ebee1cfd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>cb186125-71bf-42f8-9d3b-340bf4ea0f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5 PC DINING SET METAL</value>
      <webElementGuid>30543575-719e-4b6a-baec-0c2d34d192c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products&quot;)/div[@class=&quot;facetsearch-container row ng-scope&quot;]/div[@class=&quot;col-lg-12 col-md-12&quot;]/section[@class=&quot;facetSearch medium&quot;]/div[@class=&quot;facet-data-container&quot;]/div[@class=&quot;facet-data&quot;]/div[@class=&quot;row facetrow fieldsRow&quot;]/div[@class=&quot;searchFields touch-friendly&quot;]/div[@class=&quot;row facetrow&quot;]/div[@class=&quot;col-lg-12 col-md-12&quot;]/div[@class=&quot;col-lg-12 col-md-12 search-grid&quot;]/div[@class=&quot;touch-scroll-fields&quot;]/div[@class=&quot;touch-search-field ng-scope&quot;]/div[@class=&quot;col-lg-3 col-md-3 grid-item touch-field-value merchandisingLevel_3&quot;]/div[@class=&quot;grid-content&quot;]/div[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>b94ccb9d-d75b-4eee-8e27-b416e9896d8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='products']/div/div/section/div[2]/div/div/div[2]/div/div/div/div[2]/div[3]/div/div/div</value>
      <webElementGuid>d7bc3635-ad81-445d-970f-57bab2975a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div</value>
      <webElementGuid>4744418f-a584-4dd7-adf6-ef53e18bed74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '5 PC DINING SET METAL' or . = '5 PC DINING SET METAL')]</value>
      <webElementGuid>3a6c9f90-c3e1-47d0-8678-09de9fb97230</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
