<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Original Order 910-11230359567</name>
   <tag></tag>
   <elementGuidId>191def36-1c48-4e1a-9bf6-d26bfe0e9c06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='originalOrderNo']/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>27d69a35-3ffd-40a3-a715-0c200c9155c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>46d63b45-9310-4555-a119-84bc5aacc4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Original Order #910-11230359567</value>
      <webElementGuid>e93623c0-3ad6-46c5-b797-4d9cddf68e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;originalOrderNo&quot;)/h4[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>90085d92-6a44-46ff-aaa7-a7b5f7ac121d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='originalOrderNo']/h4</value>
      <webElementGuid>f68a7237-4a3f-4ee4-8e15-623827ef7fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>9c30fbd4-767b-4966-84f3-6b060e2d41a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Original Order #910-11230359567' or . = 'Original Order #910-11230359567')]</value>
      <webElementGuid>31ffa78d-efbd-4fb4-a483-3362b3a54c9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
