<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputsearchString</name>
   <tag></tag>
   <elementGuidId>e7740b3e-157e-4ed2-963f-6d4fd8ac82dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchString']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchString</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94915d18-ba11-4d14-b98a-d25ab095ad15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c712d224-b0bf-4043-941c-a3d297752ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchString</value>
      <webElementGuid>c161c688-9284-4949-a8b6-8f425a908c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>searchString</value>
      <webElementGuid>b7e13f4b-1c3a-4f46-bd0b-0a23d2a13e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>searchByText()</value>
      <webElementGuid>2ab24499-9754-4591-b243-123d7991ee74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-search form-control ng-untouched ng-valid ng-dirty ng-valid-parse</value>
      <webElementGuid>7fb503ea-7059-4cfa-820c-e8344a7e3c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type your search here</value>
      <webElementGuid>37690089-2d23-4c33-b264-06cdc56c5883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>1ab9bb59-a484-45c5-9570-2785fdd500fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchString&quot;)</value>
      <webElementGuid>8d2c3743-0367-4801-99a7-8b8c1140a63a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchString']</value>
      <webElementGuid>39a1c430-ea71-4a56-9e2a-e35e5eeebf0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='products']/div/div/section/div/div[2]/input</value>
      <webElementGuid>d2aa2575-ce71-4033-ac1a-7f4012091736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>5e5045b7-c683-429a-8bd9-ede40adf7b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchString' and @placeholder = 'Type your search here' and @type = 'search']</value>
      <webElementGuid>d2a7b2b1-8e1d-4136-814e-a9d0e8cf4a4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
