<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>spanretItemBtnDH736</name>
   <tag></tag>
   <elementGuidId>c62eb11a-e251-4fcb-9177-2e6bd30af4dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#retItemBtnDH736</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='retItemBtnDH736']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8e8fda0b-c778-4b24-a33b-8f0f548e6854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group-addon glyphicons bordered undo click</value>
      <webElementGuid>7be4b0aa-809f-4212-bbf0-8ee249c7c1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>returnItem(item)</value>
      <webElementGuid>9d627393-d90c-4374-a592-f447c8e40aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Return item</value>
      <webElementGuid>47076242-2dd1-454f-9a9a-9ea86a4a8c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>retItemBtnDH736</value>
      <webElementGuid>57c9e291-b2af-475d-9fa5-f6cd99b1d716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;retItemBtnDH736&quot;)</value>
      <webElementGuid>0f709892-70ff-4bb0-904c-cd540638d67d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='retItemBtnDH736']</value>
      <webElementGuid>7ea4db14-55ca-4e36-b0ea-fb8128635114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='retReturn']/span</value>
      <webElementGuid>0e03be43-531c-47f8-970c-cc63acd9adcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>cae37794-2b96-4c20-ab93-5ebd7d99b643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Return item' and @id = 'retItemBtnDH736']</value>
      <webElementGuid>18be8347-1fe0-49e6-8f2e-60d8a4973283</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
