<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Reason</name>
   <tag></tag>
   <elementGuidId>ca26c9d6-eb9b-409a-bcd5-89144d0bfce1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='return-list']/div[3]/div/div[2]/div/list/div/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cfef8a18-103a-4c6b-a73a-aee85444656e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-value ng-binding</value>
      <webElementGuid>694d10c7-b882-47ea-a268-7335e14879b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-hide</name>
      <type>Main</type>
      <value>selectedValue</value>
      <webElementGuid>d4484802-70cc-4f1a-8dd4-f81613ab4fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Reason</value>
      <webElementGuid>cbac6cf5-db91-4a9b-a72b-9066cb623db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;return-list&quot;)/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;col-lg-12 col-md-12 item bg-warning&quot;]/div[@class=&quot;row ng-scope bg-info&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-md-offset-1 pull-right&quot;]/list[@class=&quot;form-control ng-pristine ng-untouched ng-valid ng-isolate-scope has-error&quot;]/div[@class=&quot;list-container  ng-scope&quot;]/div[@class=&quot;list-placeholder&quot;]/span[@class=&quot;list-value ng-binding&quot;]</value>
      <webElementGuid>4282cb16-a352-471a-bef5-31778dcd5b70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='return-list']/div[3]/div/div[2]/div/list/div/div/span[2]</value>
      <webElementGuid>53c7f3af-4f77-4d96-bdde-03de8e5012bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//list/div/div/span[2]</value>
      <webElementGuid>a4bdea0b-470d-4d77-bf18-9f535dde85d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select Reason' or . = 'Select Reason')]</value>
      <webElementGuid>7f5c1977-e0ca-4caf-a0bf-9b988b9ad9d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
