<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_ng-binding_1</name>
   <tag></tag>
   <elementGuidId>04170e84-aa4e-4ca3-afed-e337e99f9b33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='searchResult']/div/table/tbody/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d34b26ad-bf1f-4453-b8e7-1d436837cb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>833da2bd-6b96-4265-be27-d143f33abe22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchResult&quot;)/div[@class=&quot;ng-scope&quot;]/table[@class=&quot;table table-striped table-bordered table-hover table-responsive active table-item&quot;]/tbody[1]/tr[@class=&quot;ng-scope success&quot;]/td[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>96561f26-9685-47d6-8df7-eaab135dcbc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchResult']/div/table/tbody/tr/td</value>
      <webElementGuid>831e963c-ce2d-4f85-b255-c7e530c54232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>d1521546-d07f-4a9f-943b-7b27f6d5cf0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
