<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_pull-right ng-untouched ng-valid n_4978e6</name>
   <tag></tag>
   <elementGuidId>6b00b0ae-0da3-4e43-9518-184fa9bbce08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.pull-right.ng-untouched.ng-valid.ng-valid-maxlength.ng-dirty.ng-valid-parse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='return-list']/div[4]/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>cfd87a5f-c79c-4861-abb9-4c91393f7f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-right ng-untouched ng-valid ng-valid-maxlength ng-dirty ng-valid-parse</value>
      <webElementGuid>211bf693-f524-450b-966f-426f838c0045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0ebff895-1e3e-4201-8077-ce6e45e4515f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>105</value>
      <webElementGuid>385b1ec4-4645-4e6f-9198-d1e0a496a269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>e153a7fd-3381-49f2-858d-14517815b3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>cart.Comments</value>
      <webElementGuid>7a1de521-9613-4608-92b7-9b8d0b8c2058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Additional Comments</value>
      <webElementGuid>40d530f1-29f7-4655-8185-683d3779b961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;return-list&quot;)/div[@class=&quot;row ng-scope&quot;]/div[@class=&quot;col-lg-12 col-md-12&quot;]/textarea[@class=&quot;pull-right ng-untouched ng-valid ng-valid-maxlength ng-dirty ng-valid-parse&quot;]</value>
      <webElementGuid>67b568ed-c780-457e-8948-8a671e120190</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='return-list']/div[4]/div/textarea</value>
      <webElementGuid>b90893c4-8510-411e-8dc6-893320987014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>5ef3615f-dc67-40a5-a232-6bf7d29f53bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Additional Comments']</value>
      <webElementGuid>49a25599-7905-406a-b78e-716ea4066f1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
