<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Login failed. Please check your credentials</name>
   <tag></tag>
   <elementGuidId>d9b13119-c3ce-49c8-a850-51ffac9e4434</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divWarning']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#divWarning</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c2124093-9dc5-4096-a8ba-7ffe3090dcbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>divWarning</value>
      <webElementGuid>63a014eb-9d10-4b65-b894-f2f15c9b2651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-warning text-center</value>
      <webElementGuid>9f95d984-5da4-4c29-8b4e-156262d01cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login failed. Please check your credentials.</value>
      <webElementGuid>9a2f7f91-74d5-4562-94fb-c951cd353d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divWarning&quot;)</value>
      <webElementGuid>48520cea-7dcb-4e40-82ea-afca0f8ba49f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='divWarning']</value>
      <webElementGuid>a52b0083-af95-4c8e-bf61-f14226bd4fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divErrorWrapper']/div</value>
      <webElementGuid>95ca71d1-c3f3-4401-a523-160d7901fe85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div</value>
      <webElementGuid>f1348502-13a6-41dd-9ce3-8dbf47d0bb90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'divWarning' and (text() = 'Login failed. Please check your credentials.' or . = 'Login failed. Please check your credentials.')]</value>
      <webElementGuid>5fcc3b9c-6ab0-4068-af6e-15f2c7dc62c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
