<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Customer FeedbackHappy Call</name>
   <tag></tag>
   <elementGuidId>5b677edd-642d-4775-8044-cf406bc147da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='mainMenu']/li[6]/ul/li/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>54eeef5c-745b-4ddc-be11-8b835ee817ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Cosacs/Report/DynamicReport/CustomerFeedbackHappyCall</value>
      <webElementGuid>841165bc-e90b-4304-a991-928d27adc3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>96914fbd-dc6d-40ab-9fc5-6eb31c8d13b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer Feedback/Happy Call</value>
      <webElementGuid>e1f4e803-a97c-4974-91fc-b70258b5208f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainMenu&quot;)/li[@class=&quot;dropdown ng-scope open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[@class=&quot;ng-scope dropdown-submenu&quot;]/ul[@class=&quot;dropdown-menu ng-scope&quot;]/li[@class=&quot;ng-scope&quot;]/a[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>251a38b7-430a-46a1-9ecc-f9263402eec0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenu']/li[6]/ul/li/ul/li[4]/a</value>
      <webElementGuid>ef04bcae-7931-4f02-82bc-3a8412a93457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Customer Feedback/Happy Call')]</value>
      <webElementGuid>fc38bc9d-49e7-41f7-9d68-17b5d77acd32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Cosacs/Report/DynamicReport/CustomerFeedbackHappyCall')]</value>
      <webElementGuid>1d5fe917-b7a0-4c51-85a4-a53a91a2d463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li/ul/li[4]/a</value>
      <webElementGuid>70472b49-9ff4-4966-8005-933803634ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Cosacs/Report/DynamicReport/CustomerFeedbackHappyCall' and (text() = 'Customer Feedback/Happy Call' or . = 'Customer Feedback/Happy Call')]</value>
      <webElementGuid>5e9ba78a-7f79-4e71-9b3d-90ce06d5ff98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
