<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Search My Jobs</name>
   <tag></tag>
   <elementGuidId>594f9f54-4862-494a-88b8-2e4a1e640880</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='mainMenu']/li[6]/ul/li[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c9760a70-4f16-47f7-a66a-b11daf090425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Cosacs/Service/TechnicianDiaries/SearchMyJobs</value>
      <webElementGuid>8a15ad0b-d40e-4ea0-b09c-e71377570a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>4ec69572-2ad8-4d8c-9612-cc37a3ae2282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search My Jobs</value>
      <webElementGuid>d414fb40-889d-482a-ac98-e22d923b379a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainMenu&quot;)/li[@class=&quot;dropdown ng-scope open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[@class=&quot;ng-scope&quot;]/a[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>e4cc783f-abf3-40df-8ed6-9fbb8132beb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenu']/li[6]/ul/li[6]/a</value>
      <webElementGuid>43cccf7e-b30f-445e-badf-b757643a2f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Search My Jobs')]</value>
      <webElementGuid>e4caa0f1-7769-466f-8ead-c41e96d4e663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Cosacs/Service/TechnicianDiaries/SearchMyJobs')]</value>
      <webElementGuid>da9688f1-1fc1-45b6-8ae1-ab07151cd2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li[6]/a</value>
      <webElementGuid>2c588d59-7e17-4fb6-bded-07bcd4558cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Cosacs/Service/TechnicianDiaries/SearchMyJobs' and (text() = 'Search My Jobs' or . = 'Search My Jobs')]</value>
      <webElementGuid>9b527c96-3f7a-4a32-afa7-7bf7ded3d9ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
