<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Technician Rejections</name>
   <tag></tag>
   <elementGuidId>76c91d47-e3cc-4f67-940d-1831d09919f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='mainMenu']/li[6]/ul/li/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c28022ed-9b24-456e-a2c5-242a5bf1d802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Cosacs/Report/DynamicReport/TechnicianRejections</value>
      <webElementGuid>bec77d26-0e57-47c9-83ab-ce5b07d87480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>6eba4965-ee3c-41bb-afb8-7acbdf69a587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Technician Rejections</value>
      <webElementGuid>952fa7c0-961c-4e67-802c-afb246de347f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainMenu&quot;)/li[@class=&quot;dropdown ng-scope open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[@class=&quot;ng-scope dropdown-submenu&quot;]/ul[@class=&quot;dropdown-menu ng-scope&quot;]/li[@class=&quot;ng-scope&quot;]/a[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>a280399c-9477-4bc6-be40-dd20b4a44225</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenu']/li[6]/ul/li/ul/li[2]/a</value>
      <webElementGuid>82a7e8ec-2e0e-4748-97dd-cd36cd9eab18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Technician Rejections')]</value>
      <webElementGuid>60aa9fb6-51c3-4475-a25b-55e2e84c58b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Cosacs/Report/DynamicReport/TechnicianRejections')]</value>
      <webElementGuid>482ebd45-d9f3-4f65-9063-f6656a959705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li/ul/li[2]/a</value>
      <webElementGuid>fcaf75d5-9b91-4fe4-b29f-9d4eba40e846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Cosacs/Report/DynamicReport/TechnicianRejections' and (text() = 'Technician Rejections' or . = 'Technician Rejections')]</value>
      <webElementGuid>24c3877d-ea03-4c2c-bcd4-45c3da366df4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
