<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>153b8a4a-25b2-4d1f-91ab-b868838e65e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7c10c8a3-9f8d-4a6f-b733-c099c7923977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonSearch</value>
      <webElementGuid>9ab3857b-c248-422e-979d-d93bda3a99cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search btn btn-primary</value>
      <webElementGuid>28dd4bc3-90c9-41af-918d-c7f3efdebea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>searchOrder()</value>
      <webElementGuid>d252f499-45d5-4972-b285-e11436854b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>3cc9f078-6c14-465b-96b5-5dabbf31e925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonSearch&quot;)</value>
      <webElementGuid>b954aa5b-c60a-4996-8274-d6f07f363f47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttonSearch']</value>
      <webElementGuid>b28a924d-d7ef-435c-98dc-20395203c6e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='body']/div/div/div[2]/button[2]</value>
      <webElementGuid>87cca16b-ea27-4406-9f85-4165fbfda653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>2737959c-1270-458b-89db-0d569dfa07bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buttonSearch' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>13f4de1c-2d7f-4ebb-9f8c-6bcb6b4d5c1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
