<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_910 COURTS CROSS ROADS</name>
   <tag></tag>
   <elementGuidId>8551ddaa-4c99-4ac3-9051-e51d00df2eef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.list-item.ng-binding.ng-scope.selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//list[@id='branchNo']/div[3]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d1d1d75a-9581-4c9e-9c4d-db72abc35c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-item ng-binding ng-scope selected</value>
      <webElementGuid>ce5b1c25-20c7-4084-be6f-63e8729a5b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>list.length > 0</value>
      <webElementGuid>c1d6cf51-225e-4008-ba31-d107df00dd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>item in list | filter:search</value>
      <webElementGuid>f9e05f0a-06c8-45da-90f3-bd643d940800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>selectItem(item)</value>
      <webElementGuid>8d4de88d-a90d-4f7e-8333-3dafa3909cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idx</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b0832428-3a9d-4b0c-b15a-54e55973a92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'selected':hoveredIndex == $index}</value>
      <webElementGuid>a71f17f9-7967-4f4b-ad56-b3c3aed873cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseover</name>
      <type>Main</type>
      <value>hoverItem($index)</value>
      <webElementGuid>6df45528-916b-4354-b2d9-65b8380d9207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseleave</name>
      <type>Main</type>
      <value>resetHoverItem()</value>
      <webElementGuid>99fbb2b0-de31-49c3-b027-d97a2cf8ea2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>910 COURTS CROSS ROADS</value>
      <webElementGuid>382e6876-a23d-462c-9b8d-d76b49beb9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branchNo&quot;)/div[@class=&quot;list-options ng-scope&quot;]/div[@class=&quot;list-item-container ng-scope&quot;]/div[@class=&quot;list-item ng-binding ng-scope selected&quot;]</value>
      <webElementGuid>46304756-5292-4747-a183-de00b1dc5a5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//list[@id='branchNo']/div[3]/div[2]/div</value>
      <webElementGuid>7bf9c203-f8fb-458a-a158-572645241a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div</value>
      <webElementGuid>55ffa8e4-1b5c-4321-b72c-50ed7ea250e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '910 COURTS CROSS ROADS' or . = '910 COURTS CROSS ROADS')]</value>
      <webElementGuid>69de3485-b4db-4458-a24a-a3ffa0061f0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
