<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_There are no values matching your searc_10225f</name>
   <tag></tag>
   <elementGuidId>64188383-1082-47c9-b355-3d8e2e9609f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchResult > div.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='searchResult']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>41446631-a2f8-4a85-8f25-b08ea670a282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!dataAvailable</value>
      <webElementGuid>6484bfd5-0e90-431e-9476-9ab7a2fc0fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>be7b4120-af08-4111-bd6c-b709a865f506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            There are no values matching your search filter.
        </value>
      <webElementGuid>eb1127be-f8e0-44a1-abe5-171fe173ccb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchResult&quot;)/div[@class=&quot;ng-scope&quot;]</value>
      <webElementGuid>6f7461e5-ec87-4994-b5a5-dcba94cd4587</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchResult']/div[2]</value>
      <webElementGuid>b3173e24-4ea6-4160-bacc-9c061f469806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>ebc525bf-1a7e-4edf-808a-678c05837a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
            There are no values matching your search filter.
        ' or . = '
            There are no values matching your search filter.
        ')]</value>
      <webElementGuid>6675b111-1de2-481a-b5b8-b059d16674f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
