<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>a51e3828-3221-4e4d-938d-690983142f53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonSearchExistingData</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonSearchExistingData']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c77f1bb2-e888-4d62-88df-4ed9ace4cb45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonSearchExistingData</value>
      <webElementGuid>1cf43195-18d1-448d-9f73-78967ffbd31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-lg-2 col-md-2 search btn btn-default btn-primary</value>
      <webElementGuid>9c94f5ef-68ca-4071-8ee1-df218e440527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>searchExistingData()</value>
      <webElementGuid>16993d1e-d2bd-4b7a-953c-369bf80753d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Search
                </value>
      <webElementGuid>caeb29f3-922b-444d-9e65-59643cf134ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonSearchExistingData&quot;)</value>
      <webElementGuid>b8046853-a1f7-4bfc-946d-a127a9a27801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttonSearchExistingData']</value>
      <webElementGuid>11c01d5d-57d8-4332-ab53-28917d8aa427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='body']/div/div/fieldset/div/button</value>
      <webElementGuid>e29e41fe-b400-4888-9b5d-561515fd3776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/button</value>
      <webElementGuid>1a70ebcc-2e43-4a29-8891-748cd2b32c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buttonSearchExistingData' and (text() = '
                    Search
                ' or . = '
                    Search
                ')]</value>
      <webElementGuid>911c1e63-7f00-4d48-bf54-c2c6fc2629fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
