<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Non Courts</name>
   <tag></tag>
   <elementGuidId>360ae0fd-d7c4-41d0-bec5-8727193af55b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.list-item.ng-binding.ng-scope.selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='body']/div/div/fieldset/div/div[2]/list/div[3]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5dbf20c5-af3b-4619-858d-268c2963ee72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-item ng-binding ng-scope selected</value>
      <webElementGuid>1678f38d-bcdc-4e2f-8a68-320ec8995471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>list.length > 0</value>
      <webElementGuid>a9acab5d-ad98-429c-87ed-3d86170c2646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>item in list | filter:search</value>
      <webElementGuid>b32629b3-46e7-4fc4-9f88-77606fb7a197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>selectItem(item)</value>
      <webElementGuid>44599024-46a1-4f58-96d8-cfbd3dad4e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idx</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>99768ab9-3d9a-4987-ab64-b82a2f9dceb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'selected':hoveredIndex == $index}</value>
      <webElementGuid>4e24b09b-eed1-4d7d-9c20-bcee2db7af72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseover</name>
      <type>Main</type>
      <value>hoverItem($index)</value>
      <webElementGuid>06c9c441-f7be-4c1c-9397-f120f7e65520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseleave</name>
      <type>Main</type>
      <value>resetHoverItem()</value>
      <webElementGuid>58006976-bb45-40a1-a175-e4c28b1295d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Non Courts</value>
      <webElementGuid>840fe85b-d55d-46d6-93bb-75f09c19c62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;pos-sales ng-scope&quot;]/div[@class=&quot;row form-horizontal&quot;]/fieldset[1]/div[@class=&quot;col-lg-12 col-md-12 form-group&quot;]/div[@class=&quot;col-lg-3 col-md-3&quot;]/list[@class=&quot;form-control-static container-class ng-pristine ng-untouched ng-valid ng-isolate-scope&quot;]/div[@class=&quot;list-options ng-scope&quot;]/div[@class=&quot;list-item-container ng-scope&quot;]/div[@class=&quot;list-item ng-binding ng-scope selected&quot;]</value>
      <webElementGuid>0fc2bea6-f943-4558-9840-02da21637a0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='body']/div/div/fieldset/div/div[2]/list/div[3]/div[2]/div[2]</value>
      <webElementGuid>fca49a8a-bb57-41b7-8206-a88c54cf4aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>47872010-2242-4226-b80b-ce28a84d63a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Non Courts' or . = 'Non Courts')]</value>
      <webElementGuid>b30dea9e-70cc-4ebf-931c-a1f25cfd8f91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
