<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Courts</name>
   <tag></tag>
   <elementGuidId>b6001816-2dcc-43e8-9162-151ed02c65b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.list-item.ng-binding.ng-scope.selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;body&quot;]/div/div[1]/fieldset/div/div[2]/list/div[3]/div[2]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fd3dc304-395b-4c4c-a696-129c50dcd51f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-item ng-binding ng-scope selected</value>
      <webElementGuid>a68ed9d2-d6aa-4359-92a1-dc7ac079178e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>list.length > 0</value>
      <webElementGuid>23727656-b42c-4d71-9daf-37a38c32f00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>item in list | filter:search</value>
      <webElementGuid>814bd210-70d6-4553-9d9c-073c5479be1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>selectItem(item)</value>
      <webElementGuid>02ff9ee3-1982-4f1b-b6f2-e7bfffe34a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idx</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6980ef62-51ec-4b9d-8f94-1e75f39f35f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'selected':hoveredIndex == $index}</value>
      <webElementGuid>b4a7af8e-4fd9-46f8-8d5b-651411d49a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseover</name>
      <type>Main</type>
      <value>hoverItem($index)</value>
      <webElementGuid>ba6bab0f-5de6-4485-b367-c6b505bc0309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseleave</name>
      <type>Main</type>
      <value>resetHoverItem()</value>
      <webElementGuid>b8bcfb75-6528-41d0-b91e-4ccf2336d65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Courts</value>
      <webElementGuid>aea3864b-9c8a-458c-aa77-7ac0f0a2cef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;pos-sales ng-scope&quot;]/div[@class=&quot;col-lg-9 col-md-9 col-md-offset-1&quot;]/table[@class=&quot;data table table-striped table-bordered table-hover table-responsive col-lg-10 col-md-10&quot;]/tbody[1]/tr[1]/td[@class=&quot;col-lg-3 col-md-3&quot;]/list[@class=&quot;form-control-static ng-pristine ng-untouched ng-valid ng-scope ng-isolate-scope&quot;]/div[@class=&quot;list-options ng-scope&quot;]/div[@class=&quot;list-item-container ng-scope&quot;]/div[@class=&quot;list-item ng-binding ng-scope selected&quot;]</value>
      <webElementGuid>73c14e11-4332-43d7-9b97-bdc49be8a370</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='body']/div/div[2]/table/tbody/tr/td[2]/list/div[3]/div[2]/div</value>
      <webElementGuid>436f25e9-801e-4a23-a138-3ac6bd759897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div</value>
      <webElementGuid>79928245-7695-4540-9222-d6d5dcb1f276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Courts' or . = 'Courts')]</value>
      <webElementGuid>44733449-74ee-4ba2-85f7-946ce90be981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='body']/div/div/fieldset/div/div[2]/list/div[3]/div[2]/div</value>
      <webElementGuid>9b13f6c9-aae5-4c3a-8749-570051332bcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
