<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_glyphicons play</name>
   <tag></tag>
   <elementGuidId>a3e66b29-fd24-458e-a245-58ecf3c49408</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.glyphicons.search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='body']/div/div[2]/table/tbody/tr/td[2]/list/div[3]/div/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>dab8528b-02f5-406f-82cd-438ef88766e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons search</value>
      <webElementGuid>1aa5f44e-c62e-4e9d-8733-ce623dccf5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;pos-sales ng-scope&quot;]/div[@class=&quot;col-lg-9 col-md-9 col-md-offset-1&quot;]/table[@class=&quot;data table table-striped table-bordered table-hover table-responsive col-lg-10 col-md-10&quot;]/tbody[1]/tr[1]/td[@class=&quot;col-lg-3 col-md-3&quot;]/list[@class=&quot;form-control-static ng-pristine ng-untouched ng-valid ng-scope ng-isolate-scope&quot;]/div[@class=&quot;list-options ng-scope&quot;]/div[@class=&quot;list-search ng-scope&quot;]/div[@class=&quot;list-search-icon&quot;]/div[1]/i[@class=&quot;glyphicons search&quot;]</value>
      <webElementGuid>6a72a690-6fee-41cb-84cb-a9f2badc754a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='body']/div/div[2]/table/tbody/tr/td[2]/list/div[3]/div/div/div/i</value>
      <webElementGuid>174ff8b9-f367-4944-a66c-f529c2692828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/i</value>
      <webElementGuid>e4b79d91-6442-4470-a351-998b0fc44def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='body']/div/div[2]/table/tbody/tr/td[2]/list/div/div[3]/div/i</value>
      <webElementGuid>a52c7e2e-fb53-47b1-bded-326ae8a95d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/list/div/div[3]/div/i</value>
      <webElementGuid>cd8de785-85b7-4f36-b753-6b21dcab6dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='body']/div/div/fieldset/div/div[2]/list/div/div[3]/div/i</value>
      <webElementGuid>9592c7e2-ab6c-4e65-bd27-40d976ad6da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/i</value>
      <webElementGuid>c4fb19fe-110c-40a6-ad5f-e1c04edce495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='body']/div/div[2]/table/tbody/tr/td[3]/list/div/div[3]/div/i</value>
      <webElementGuid>19402040-7b72-44a1-9e00-81272536e27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/list/div/div[3]/div/i</value>
      <webElementGuid>af38e44c-f0e0-4d4f-8c92-50a79a13111d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
