<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_form-control text-right ng-untouched _146de2</name>
   <tag></tag>
   <elementGuidId>8a8d36be-e970-41e4-bb87-cba77c1e8237</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.text-right.ng-untouched.ng-valid.ng-scope.ng-valid-max.ng-valid-pattern.ng-dirty.ng-valid-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4d7167a-7d7c-4908-b6d8-53714124a36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-right ng-untouched ng-valid ng-scope ng-valid-max ng-valid-pattern ng-dirty ng-valid-number</value>
      <webElementGuid>8f8b8a5e-903b-4b2b-90e8-56111d402af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>showNewRow</value>
      <webElementGuid>8c1bc107-8454-4dbe-8bb3-535e0c2fa82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>newData.limitPercentage</value>
      <webElementGuid>2b4d0e36-9e8a-4ca0-b38b-580ac3f6479a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7e863bbe-34ff-4c2b-b7ae-bc410310a57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^[0-9]+(\.[0-9]{1,2})?$/</value>
      <webElementGuid>7418138c-d759-4237-82db-598819611cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>6789ab69-33a6-4c2c-a22f-b3b2846953e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;pos-sales ng-scope&quot;]/div[@class=&quot;col-lg-9 col-md-9 col-md-offset-1&quot;]/table[@class=&quot;data table table-striped table-bordered table-hover table-responsive col-lg-10 col-md-10&quot;]/tbody[1]/tr[1]/td[@class=&quot;col-lg-2 col-md-2&quot;]/div[1]/input[@class=&quot;form-control text-right ng-untouched ng-valid ng-scope ng-valid-max ng-valid-pattern ng-dirty ng-valid-number&quot;]</value>
      <webElementGuid>a82da454-2543-4be2-ab95-c39ece293070</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='number']</value>
      <webElementGuid>cafc3688-d82b-49b5-bdf4-31ae04a89d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='body']/div/div[2]/table/tbody/tr/td[4]/div/input</value>
      <webElementGuid>618d9193-2a05-4c1a-8996-0628da117a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/input</value>
      <webElementGuid>07487131-7274-490b-bb8b-5ce231d884f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>bceb05e1-9941-4349-9f97-cfc365c3e603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='body']/div/div[2]/table/tbody/tr[2]/td[4]/div/input</value>
      <webElementGuid>fe76ff92-373e-4d1f-ae8c-c45e8750892a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
