<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Record added successfully</name>
   <tag></tag>
   <elementGuidId>2092cecc-c8d7-484e-a4a7-51760a31970e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.growl-message.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>61b3df6d-19eb-4155-acdd-61e50daa750f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-bind-html</name>
      <type>Main</type>
      <value>growl.content</value>
      <webElementGuid>14678d64-28f9-4958-afed-05f0c5899ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>growl-message ng-binding</value>
      <webElementGuid>3d066e7b-4e39-4e2b-b6af-e6d92aadd962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Record added successfully</value>
      <webElementGuid>b3ee25e7-d9e5-4cbd-9a8d-e3b5289417ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;ng-scope&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;growl-container growl-fixed.top-center row&quot;]/article[@class=&quot;growl-item ng-scope&quot;]/div[@class=&quot;alert alert-success alert-dismissable&quot;]/p[@class=&quot;growl-message ng-binding&quot;]</value>
      <webElementGuid>d846db90-6e14-4953-bf57-bac775c764be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>23961337-0957-463a-bb1c-885e78ecf855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Record added successfully' or . = 'Record added successfully')]</value>
      <webElementGuid>a9b8e9b9-79ab-4272-911b-1cbdc3983301</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
