<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Record deleted successfully</name>
   <tag></tag>
   <elementGuidId>1079af04-7d32-4efd-a330-c1507cc53814</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.growl-message.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3cbaebb7-fa08-4903-99a1-fa98a449e4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-bind-html</name>
      <type>Main</type>
      <value>growl.content</value>
      <webElementGuid>1453f5a2-dd3b-457d-a271-c9379e097478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>growl-message ng-binding</value>
      <webElementGuid>75b81a24-02a9-4373-9cc7-84970ff6fac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Record deleted successfully</value>
      <webElementGuid>6ab618d7-c441-49e4-8ac6-143e7cc5039e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;ng-scope&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;growl-container growl-fixed.top-center row&quot;]/article[@class=&quot;growl-item ng-scope&quot;]/div[@class=&quot;alert alert-success alert-dismissable&quot;]/p[@class=&quot;growl-message ng-binding&quot;]</value>
      <webElementGuid>66bc1b80-2465-4b28-b2c9-dc269f70ce5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>ff53eddc-43dd-4eeb-84a5-18cf0d129859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Record deleted successfully' or . = 'Record deleted successfully')]</value>
      <webElementGuid>9b4ab031-72ef-4637-b301-0e5501f547ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
