<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_All Store Type</name>
   <tag></tag>
   <elementGuidId>06c49ee4-d6a6-48c0-b78b-1ce1c15ca44c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='body']/div/div[2]/table/tbody/tr/td[2]/list/div/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>02669594-e685-42b9-831a-8a169e63af1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-value ng-binding</value>
      <webElementGuid>4acd29f2-162d-4506-b78c-5f59a0548ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-hide</name>
      <type>Main</type>
      <value>selectedValue</value>
      <webElementGuid>aefbe361-754c-4f9d-b95c-fc88a8210e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Store Type</value>
      <webElementGuid>86231818-cd7e-4f57-b1b9-d28fb598a2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;pos-sales ng-scope&quot;]/div[@class=&quot;col-lg-9 col-md-9 col-md-offset-1&quot;]/table[@class=&quot;data table table-striped table-bordered table-hover table-responsive col-lg-10 col-md-10&quot;]/tbody[1]/tr[1]/td[@class=&quot;col-lg-3 col-md-3&quot;]/list[@class=&quot;form-control-static ng-pristine ng-untouched ng-valid ng-scope ng-isolate-scope&quot;]/div[@class=&quot;list-container  ng-scope&quot;]/div[@class=&quot;list-placeholder&quot;]/span[@class=&quot;list-value ng-binding&quot;]</value>
      <webElementGuid>5d8bc615-dc49-42fd-8092-a74339702903</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='body']/div/div[2]/table/tbody/tr/td[2]/list/div/div/span[2]</value>
      <webElementGuid>3a63ff3e-d5de-4569-83d9-344fb969c7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/list/div/div/span[2]</value>
      <webElementGuid>30f650df-64e4-4ed6-b42c-380c77124eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'All Store Type' or . = 'All Store Type')]</value>
      <webElementGuid>8f0c03c4-f2fe-4a9e-8170-17c2b38bc470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='body']/div/div/fieldset/div/div[2]/list/div/div/span[2]</value>
      <webElementGuid>019a43fd-7edc-43d3-8cbf-7460be376a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[2]</value>
      <webElementGuid>aeaa8f00-97a1-4bec-93e5-710c3d7ab53a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
