<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_glyphicons plus click glyph-btn ng-scope</name>
   <tag></tag>
   <elementGuidId>9aecd2c4-d802-4a70-8468-b1672969f9c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.glyphicons.plus.click.glyph-btn.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='body']/div/div[2]/table/tbody/tr/td/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>716d6aa4-22ed-49df-973e-1332427b8866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons plus click glyph-btn ng-scope</value>
      <webElementGuid>b4ac326a-4e18-4898-af6f-c400a553299b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!showNewRow</value>
      <webElementGuid>74417816-9369-479e-ba83-1d5b4f77838d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>6f73d314-2551-4229-ab8d-bd51f2678bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>addNew()</value>
      <webElementGuid>7b73c979-f113-4195-b302-e6ad00596344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;pos-sales ng-scope&quot;]/div[@class=&quot;col-lg-9 col-md-9 col-md-offset-1&quot;]/table[@class=&quot;data table table-striped table-bordered table-hover table-responsive col-lg-10 col-md-10&quot;]/tbody[1]/tr[1]/td[@class=&quot;col-lg-2 col-md-2&quot;]/span[@class=&quot;glyphicons plus click glyph-btn ng-scope&quot;]</value>
      <webElementGuid>66b844bd-5aa8-44f6-9ed2-9afd03072f31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='body']/div/div[2]/table/tbody/tr/td/span</value>
      <webElementGuid>b293164d-7111-430c-8fe1-5dfcadae6c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>9826d83a-17f7-4a53-829a-eca1e08081cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'New']</value>
      <webElementGuid>9c0ee6f0-95c5-4d90-ad2f-2d446e76baa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
