<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Search</name>
   <tag></tag>
   <elementGuidId>b83ed10d-3432-402b-8a6e-b1cf995e02a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='mainMenu']/li[4]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.dropdown.ng-scope.open > ul.dropdown-menu > li.ng-scope > a.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>394c8d40-d746-4f5b-959a-4f67eccba623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/Payments/Search</value>
      <webElementGuid>774171c6-8945-4f38-a39a-e3dec78a55c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>c91ef232-dfe9-479f-b9cb-e491e2bbe35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>c6a8cfea-d051-4107-b04b-a52c90e8676d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainMenu&quot;)/li[@class=&quot;dropdown ng-scope open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[@class=&quot;ng-scope&quot;]/a[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>995499f7-c4ee-4995-b38b-4187ea5b343c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenu']/li[4]/ul/li/a</value>
      <webElementGuid>5b82bd81-3c15-49b4-8928-a6fa832e6921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Search')])[3]</value>
      <webElementGuid>4c543bb8-82a1-4e97-8844-6642f3922352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/Payments/Search')]</value>
      <webElementGuid>947dbb31-5b05-4807-ab5a-6b67e7c80b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li/a</value>
      <webElementGuid>c84f288e-a189-4e2f-b17a-6a48b9a612dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/Payments/Search' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>41e030b5-04c0-47d5-bfa4-fbaf0d04cd21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
